// Code generated by protoc-gen-go.
// source: api/feature-toggle.proto
// DO NOT EDIT!

/*
Package feature_toggle_api is a generated protocol buffer package.

It is generated from these files:
	api/feature-toggle.proto

It has these top-level messages:
	CreateFeatureRequest
	CreateFeatureResponse
	ReadFeatureRequest
	ReadFeatureResponse
	DeleteFeatureRequest
	DeleteFeatureResponse
	SearchFeatureRequest
	SearchFeatureResponse
	Feature
*/
package feature_toggle_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateFeatureRequest struct {
	Feature *Feature `protobuf:"bytes,1,opt,name=Feature" json:"Feature,omitempty"`
}

func (m *CreateFeatureRequest) Reset()                    { *m = CreateFeatureRequest{} }
func (m *CreateFeatureRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFeatureRequest) ProtoMessage()               {}
func (*CreateFeatureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateFeatureRequest) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type CreateFeatureResponse struct {
	Feature *Feature `protobuf:"bytes,1,opt,name=Feature" json:"Feature,omitempty"`
}

func (m *CreateFeatureResponse) Reset()                    { *m = CreateFeatureResponse{} }
func (m *CreateFeatureResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateFeatureResponse) ProtoMessage()               {}
func (*CreateFeatureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateFeatureResponse) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type ReadFeatureRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadFeatureRequest) Reset()                    { *m = ReadFeatureRequest{} }
func (m *ReadFeatureRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadFeatureRequest) ProtoMessage()               {}
func (*ReadFeatureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadFeatureResponse struct {
	Feature *Feature `protobuf:"bytes,1,opt,name=Feature" json:"Feature,omitempty"`
}

func (m *ReadFeatureResponse) Reset()                    { *m = ReadFeatureResponse{} }
func (m *ReadFeatureResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadFeatureResponse) ProtoMessage()               {}
func (*ReadFeatureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadFeatureResponse) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type DeleteFeatureRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteFeatureRequest) Reset()                    { *m = DeleteFeatureRequest{} }
func (m *DeleteFeatureRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFeatureRequest) ProtoMessage()               {}
func (*DeleteFeatureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteFeatureResponse struct {
}

func (m *DeleteFeatureResponse) Reset()                    { *m = DeleteFeatureResponse{} }
func (m *DeleteFeatureResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteFeatureResponse) ProtoMessage()               {}
func (*DeleteFeatureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchFeatureRequest struct {
	Filter *SearchFeatureRequest_FilterMessage `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
}

func (m *SearchFeatureRequest) Reset()                    { *m = SearchFeatureRequest{} }
func (m *SearchFeatureRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchFeatureRequest) ProtoMessage()               {}
func (*SearchFeatureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchFeatureRequest) GetFilter() *SearchFeatureRequest_FilterMessage {
	if m != nil {
		return m.Filter
	}
	return nil
}

type SearchFeatureRequest_FilterMessage struct {
	Name         string                      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Enabled      bool                        `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	CreatedStart *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=createdStart" json:"createdStart,omitempty"`
	CreatedEnd   *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=createdEnd" json:"createdEnd,omitempty"`
	ExpiresStart *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=expiresStart" json:"expiresStart,omitempty"`
	ExpiresEnd   *google_protobuf1.Timestamp `protobuf:"bytes,6,opt,name=expiresEnd" json:"expiresEnd,omitempty"`
	Properties   map[string]string           `protobuf:"bytes,7,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SearchFeatureRequest_FilterMessage) Reset()         { *m = SearchFeatureRequest_FilterMessage{} }
func (m *SearchFeatureRequest_FilterMessage) String() string { return proto.CompactTextString(m) }
func (*SearchFeatureRequest_FilterMessage) ProtoMessage()    {}
func (*SearchFeatureRequest_FilterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *SearchFeatureRequest_FilterMessage) GetCreatedStart() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedStart
	}
	return nil
}

func (m *SearchFeatureRequest_FilterMessage) GetCreatedEnd() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedEnd
	}
	return nil
}

func (m *SearchFeatureRequest_FilterMessage) GetExpiresStart() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ExpiresStart
	}
	return nil
}

func (m *SearchFeatureRequest_FilterMessage) GetExpiresEnd() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ExpiresEnd
	}
	return nil
}

func (m *SearchFeatureRequest_FilterMessage) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type SearchFeatureResponse struct {
	Features []*Feature `protobuf:"bytes,1,rep,name=Features" json:"Features,omitempty"`
}

func (m *SearchFeatureResponse) Reset()                    { *m = SearchFeatureResponse{} }
func (m *SearchFeatureResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchFeatureResponse) ProtoMessage()               {}
func (*SearchFeatureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SearchFeatureResponse) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type Feature struct {
	Id         string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Enabled    bool                        `protobuf:"varint,3,opt,name=enabled" json:"enabled,omitempty"`
	Created    *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	Expires    *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=expires" json:"expires,omitempty"`
	Properties map[string]string           `protobuf:"bytes,6,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Feature) GetCreated() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Feature) GetExpires() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Feature) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateFeatureRequest)(nil), "feature_toggle_api.CreateFeatureRequest")
	proto.RegisterType((*CreateFeatureResponse)(nil), "feature_toggle_api.CreateFeatureResponse")
	proto.RegisterType((*ReadFeatureRequest)(nil), "feature_toggle_api.ReadFeatureRequest")
	proto.RegisterType((*ReadFeatureResponse)(nil), "feature_toggle_api.ReadFeatureResponse")
	proto.RegisterType((*DeleteFeatureRequest)(nil), "feature_toggle_api.DeleteFeatureRequest")
	proto.RegisterType((*DeleteFeatureResponse)(nil), "feature_toggle_api.DeleteFeatureResponse")
	proto.RegisterType((*SearchFeatureRequest)(nil), "feature_toggle_api.SearchFeatureRequest")
	proto.RegisterType((*SearchFeatureRequest_FilterMessage)(nil), "feature_toggle_api.SearchFeatureRequest.FilterMessage")
	proto.RegisterType((*SearchFeatureResponse)(nil), "feature_toggle_api.SearchFeatureResponse")
	proto.RegisterType((*Feature)(nil), "feature_toggle_api.Feature")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeatureToggleService service

type FeatureToggleServiceClient interface {
	CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*CreateFeatureResponse, error)
	ReadFeature(ctx context.Context, in *ReadFeatureRequest, opts ...grpc.CallOption) (*ReadFeatureResponse, error)
	DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*DeleteFeatureResponse, error)
	SearchFeature(ctx context.Context, in *SearchFeatureRequest, opts ...grpc.CallOption) (*SearchFeatureResponse, error)
}

type featureToggleServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeatureToggleServiceClient(cc *grpc.ClientConn) FeatureToggleServiceClient {
	return &featureToggleServiceClient{cc}
}

func (c *featureToggleServiceClient) CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*CreateFeatureResponse, error) {
	out := new(CreateFeatureResponse)
	err := grpc.Invoke(ctx, "/feature_toggle_api.FeatureToggleService/CreateFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureToggleServiceClient) ReadFeature(ctx context.Context, in *ReadFeatureRequest, opts ...grpc.CallOption) (*ReadFeatureResponse, error) {
	out := new(ReadFeatureResponse)
	err := grpc.Invoke(ctx, "/feature_toggle_api.FeatureToggleService/ReadFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureToggleServiceClient) DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*DeleteFeatureResponse, error) {
	out := new(DeleteFeatureResponse)
	err := grpc.Invoke(ctx, "/feature_toggle_api.FeatureToggleService/DeleteFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureToggleServiceClient) SearchFeature(ctx context.Context, in *SearchFeatureRequest, opts ...grpc.CallOption) (*SearchFeatureResponse, error) {
	out := new(SearchFeatureResponse)
	err := grpc.Invoke(ctx, "/feature_toggle_api.FeatureToggleService/SearchFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeatureToggleService service

type FeatureToggleServiceServer interface {
	CreateFeature(context.Context, *CreateFeatureRequest) (*CreateFeatureResponse, error)
	ReadFeature(context.Context, *ReadFeatureRequest) (*ReadFeatureResponse, error)
	DeleteFeature(context.Context, *DeleteFeatureRequest) (*DeleteFeatureResponse, error)
	SearchFeature(context.Context, *SearchFeatureRequest) (*SearchFeatureResponse, error)
}

func RegisterFeatureToggleServiceServer(s *grpc.Server, srv FeatureToggleServiceServer) {
	s.RegisterService(&_FeatureToggleService_serviceDesc, srv)
}

func _FeatureToggleService_CreateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureToggleServiceServer).CreateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feature_toggle_api.FeatureToggleService/CreateFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureToggleServiceServer).CreateFeature(ctx, req.(*CreateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureToggleService_ReadFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureToggleServiceServer).ReadFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feature_toggle_api.FeatureToggleService/ReadFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureToggleServiceServer).ReadFeature(ctx, req.(*ReadFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureToggleService_DeleteFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureToggleServiceServer).DeleteFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feature_toggle_api.FeatureToggleService/DeleteFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureToggleServiceServer).DeleteFeature(ctx, req.(*DeleteFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureToggleService_SearchFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureToggleServiceServer).SearchFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feature_toggle_api.FeatureToggleService/SearchFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureToggleServiceServer).SearchFeature(ctx, req.(*SearchFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeatureToggleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feature_toggle_api.FeatureToggleService",
	HandlerType: (*FeatureToggleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFeature",
			Handler:    _FeatureToggleService_CreateFeature_Handler,
		},
		{
			MethodName: "ReadFeature",
			Handler:    _FeatureToggleService_ReadFeature_Handler,
		},
		{
			MethodName: "DeleteFeature",
			Handler:    _FeatureToggleService_DeleteFeature_Handler,
		},
		{
			MethodName: "SearchFeature",
			Handler:    _FeatureToggleService_SearchFeature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/feature-toggle.proto",
}

func init() { proto.RegisterFile("api/feature-toggle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xec, 0x34, 0x49, 0xa7, 0x98, 0x56, 0xdb, 0x44, 0x58, 0x06, 0x89, 0xca, 0x42, 0xa5,
	0x14, 0xe1, 0x48, 0xe5, 0x57, 0x91, 0xe0, 0x02, 0xcd, 0x05, 0x5a, 0x55, 0x4e, 0xef, 0xd5, 0x26,
	0x9e, 0x04, 0x8b, 0xc4, 0x36, 0xf6, 0x26, 0x22, 0xaa, 0xb8, 0xf0, 0x0a, 0x3c, 0x10, 0x27, 0x9e,
	0x80, 0x2b, 0x47, 0x5e, 0x03, 0x09, 0x7b, 0xbd, 0x0e, 0xb1, 0xb3, 0xc2, 0x51, 0x51, 0x6f, 0xbb,
	0xb3, 0xdf, 0x7c, 0xdf, 0xac, 0xe7, 0xdb, 0x31, 0xe8, 0x34, 0x70, 0xdb, 0x43, 0xa4, 0x6c, 0x1a,
	0xe2, 0x23, 0xe6, 0x8f, 0x46, 0x63, 0xb4, 0x82, 0xd0, 0x67, 0x3e, 0x21, 0x22, 0x7a, 0x91, 0x46,
	0x2f, 0x62, 0xa0, 0x71, 0x67, 0xe4, 0xfb, 0xf1, 0xba, 0x9d, 0x24, 0x51, 0xcf, 0xf3, 0x19, 0x65,
	0xae, 0xef, 0x45, 0x69, 0x86, 0x71, 0x57, 0x9c, 0xf2, 0x5d, 0x7f, 0x3a, 0x6c, 0x33, 0x77, 0x82,
	0x11, 0xa3, 0x93, 0x20, 0x05, 0x98, 0x27, 0xd0, 0x7c, 0x1d, 0xc6, 0xac, 0xd8, 0x4d, 0xa9, 0x6d,
	0xfc, 0x38, 0x8d, 0x01, 0xe4, 0x29, 0xd4, 0x45, 0x44, 0xaf, 0xec, 0x55, 0x0e, 0xb6, 0x8e, 0x6e,
	0x5b, 0xab, 0xe2, 0x56, 0x96, 0x94, 0x61, 0xcd, 0x53, 0x68, 0x15, 0xe8, 0xa2, 0x20, 0xae, 0x06,
	0xaf, 0xca, 0x77, 0x0f, 0x88, 0x8d, 0xd4, 0x29, 0x14, 0x77, 0x13, 0x14, 0xd7, 0xe1, 0x3c, 0x9b,
	0x76, 0xbc, 0x32, 0xdf, 0xc1, 0x6e, 0x0e, 0xf5, 0x7f, 0x9a, 0xfb, 0xd0, 0x7c, 0x83, 0x63, 0x5c,
	0xf9, 0x24, 0x45, 0xd5, 0x5b, 0xd0, 0x2a, 0xe0, 0x52, 0x5d, 0xf3, 0x7b, 0x15, 0x9a, 0x3d, 0xa4,
	0xe1, 0xe0, 0x7d, 0x81, 0xe1, 0x14, 0x6a, 0x43, 0x77, 0xcc, 0x30, 0x14, 0xf5, 0x3c, 0x93, 0xd5,
	0x23, 0xcb, 0xb4, 0xba, 0x3c, 0xed, 0x04, 0xa3, 0x88, 0x8e, 0xd0, 0x16, 0x2c, 0xc6, 0x4f, 0x15,
	0xb4, 0xdc, 0x09, 0x21, 0x50, 0xf5, 0xe8, 0x04, 0x45, 0x95, 0x7c, 0x4d, 0x74, 0xa8, 0xa3, 0x47,
	0xfb, 0x63, 0x74, 0x74, 0x25, 0x0e, 0x37, 0xec, 0x6c, 0x4b, 0x5e, 0xc1, 0x8d, 0x01, 0xef, 0x96,
	0xd3, 0x63, 0x34, 0x64, 0xba, 0xca, 0xab, 0x32, 0xac, 0xd4, 0x34, 0x56, 0x66, 0x1a, 0xeb, 0x3c,
	0x33, 0x8d, 0x9d, 0xc3, 0x93, 0x0e, 0x80, 0xd8, 0x1f, 0x7b, 0x8e, 0x5e, 0x2d, 0xcd, 0x5e, 0x42,
	0x27, 0xda, 0xf8, 0x29, 0x70, 0x43, 0x8c, 0x52, 0xed, 0x8d, 0x72, 0xed, 0x65, 0x7c, 0xa2, 0x2d,
	0xf6, 0x89, 0x76, 0xad, 0x5c, 0xfb, 0x2f, 0x9a, 0x0c, 0x01, 0x62, 0x44, 0x80, 0x21, 0x73, 0x31,
	0xd2, 0xeb, 0x7b, 0x6a, 0x9c, 0xdb, 0xbd, 0x5a, 0x2f, 0xac, 0xb3, 0x05, 0xd1, 0xb1, 0xc7, 0xc2,
	0xb9, 0xbd, 0xc4, 0x6c, 0xbc, 0x84, 0xed, 0xc2, 0x31, 0xd9, 0x01, 0xf5, 0x03, 0xce, 0x45, 0x7f,
	0x92, 0x25, 0x69, 0xc2, 0xc6, 0x8c, 0x8e, 0xa7, 0xc8, 0x9b, 0xb3, 0x69, 0xa7, 0x9b, 0x8e, 0xf2,
	0xa2, 0x62, 0x9e, 0x41, 0xab, 0x50, 0x80, 0x30, 0xf6, 0x73, 0x68, 0x88, 0x50, 0x14, 0x33, 0xa9,
	0x65, 0xce, 0x5e, 0x80, 0xcd, 0x6f, 0xca, 0xe2, 0x49, 0x14, 0xed, 0xbc, 0xb0, 0x8e, 0x22, 0xb7,
	0x8e, 0x9a, 0xb7, 0xce, 0x13, 0xa8, 0x8b, 0x66, 0xae, 0xd1, 0xf7, 0x0c, 0x9a, 0x64, 0x89, 0x36,
	0xac, 0xd1, 0xef, 0x0c, 0x4a, 0xde, 0xe6, 0xda, 0x55, 0xe3, 0x17, 0x7e, 0xf8, 0x8f, 0x0b, 0x5f,
	0x63, 0x4f, 0x8e, 0x7e, 0xab, 0xd0, 0x14, 0x32, 0xe7, 0x5c, 0xb8, 0x87, 0xe1, 0xcc, 0x1d, 0x20,
	0x99, 0x83, 0x96, 0x9b, 0x7c, 0xe4, 0x40, 0x56, 0xa1, 0x6c, 0xd6, 0x1a, 0x0f, 0xd6, 0x40, 0x8a,
	0xd1, 0xb2, 0xfb, 0xe5, 0xc7, 0xaf, 0xaf, 0x8a, 0x66, 0x36, 0xb2, 0x1f, 0x44, 0xa7, 0x72, 0x48,
	0xa6, 0xb0, 0xb5, 0x34, 0xfe, 0xc8, 0xbe, 0x8c, 0x6e, 0x75, 0x8a, 0x1a, 0xf7, 0x4b, 0x71, 0x42,
	0xb4, 0xc5, 0x45, 0xb7, 0x89, 0x96, 0x89, 0xb6, 0x2f, 0x5d, 0xe7, 0x33, 0xb9, 0x04, 0x2d, 0x37,
	0xff, 0xe4, 0x37, 0x96, 0x8d, 0x52, 0xf9, 0x8d, 0xe5, 0xc3, 0x54, 0x88, 0x1f, 0x16, 0xc4, 0x67,
	0xa0, 0xe5, 0xde, 0x86, 0x5c, 0x5c, 0xf6, 0x7e, 0xe5, 0xe2, 0xd2, 0x87, 0x66, 0xee, 0x70, 0x71,
	0x20, 0x8b, 0xcf, 0xdd, 0xaf, 0x71, 0xa3, 0x3e, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x29, 0x0d,
	0xbe, 0xbc, 0xa5, 0x07, 0x00, 0x00,
}
